### ISSUE TITLE
Minor version bump (2.0.12 -> 2.1.0) breaks gulp

### ISSUE THREAD

**Issue by Pursuit92** [js-cli/js-v8flags#35]
```
> gulp deploy

crypto.js:74
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at Object.<anonymous> (/builds/Prevoty/gozer/manager_frontend/node_modules/v8flags/index.js:14:81)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

Gulp version: git://github.com/gulpjs/gulp.git#3f5aba28718dc19e4bf600fb88f128158ff2ff83

**Comment by phated** [comment]
Literal duplicate.  Do you not even look at the issue tracker before you post?

**Comment by Pursuit92** [comment]
Did you not consider the possibility that it wasn't there then I clicked the "new issue" button? Being an asshole to people reporting bugs is a good way to drive them away.

**Comment by phated** [comment]
I did consider that, but 21 minutes vs 10...

A fix has been published.

**Comment by tkellen** [comment]
Hey guys! Same team!
