### ISSUE TITLE
Version 2.1.1 crashes with a TypeError

### ISSUE THREAD

**Issue by demurgos** [js-cli/js-v8flags#36]
Hi, I noticed that my CI builds started to fail about 30 minutes ago. It seems that it corresponds to the publication of the version `2.1.1` to _npm_. The error happens when using _gulp_ which depends on this module:

```
crypto.js:74
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:74:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp-cli/node_modules/v8flags/index.js:14:81)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp-cli/index.js:11:15)
```

I am using Node 7.9.0 on Debian Jessie inside a Docker running with Gitlab CI.

The position `14:81` corresponds to `.update(user)`. I am still investigating the issue.

**Comment by phated** [comment]
Thanks. it's already been solved...

**Comment by demurgos** [comment]
Sorry for the duplicate.
