### ISSUE TITLE
TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by testerez** [js-cli/js-v8flags#41]
After upgrading ts-node from version 3.2 to 3.3, we started having this issue on our dev server. We can't reproduce it on our mac workstations.

It seams like this is introduced by the upgrade to v8flags@3.0.0.

We are downgrading as it fixes our issue but I wanted to let you know...

```
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at linux (/opt/apps/pbv4/release/08022017145510/node_modules/v8flags/config-path.js:19:25)
    at module.exports (/opt/apps/pbv4/release/08022017145510/node_modules/v8flags/config-path.js:32:10)
    at Object.<anonymous> (/opt/apps/pbv4/release/08022017145510/node_modules/v8flags/index.js:10:47)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
error Command failed with exit code 1.
```

**Comment by phated** [comment]
Ping @Siilwyn

**Comment by Siilwyn** [comment]
Thank you for reporting, I'm responsible for this change.
This error looks like it's coming from the `user-home` module returning null. Wondering if we should have a fallback or handle it on `user-home` module level.

Could you be so kind to run the `env-paths` module on the dev server with the following result and report the result?
```js
const envPaths = require('env-paths');
const paths = envPaths('MyApp');

paths.cache
```

**Comment by philipperoy1** [comment]
@Siilwyn the result of `os.homedir()` is `/root`. 
Hope it helps !

**Comment by Siilwyn** [comment]
Thanks, that means the `user-home` is not working correctly. Could you test with `homedir-polyfill`?

**Comment by philipperoy1** [comment]
@Siilwyn :
```
user-home: null
homedir-polyfill: /root
```

**Comment by phated** [comment]
👍  on homedir-polyfill switch

**Comment by tkellen** [comment]
Nice debugging ya'll, and thanks @Siilwyn for tackling this so quickly.

**Comment by Siilwyn** [comment]
This issue goes a bit further than expected, the logic for falling back is already in place but was basically 'skipped'.
